[Etchash]
wallet = PENDING_USER
rigName = PENDING_RIG
coin = ETC
pool1 = etc.poolbinance.com:1800
pool2 = etc.poolbinance.com:25
pool3 = etc.poolbinance.com:443

sortPools = true
logToConsole = true
stdout = true

# --- PROTECCIÓN TÉRMICA (Seguridad para tu Laptop) ---
targetTemp = 70
criticalTemp = 82
# Fuerza al minero a usar solo el 60% de la capacidad de la tarjeta
lhr = 60
# Nota: fanSpeed, coreClick y memClock pueden ser ignorados por algunos drivers en WSL2
fanSpeed = 80
#coreClick = -200
#memClock = +400

# --- CONFIGURACIÓN DE LOGS ---
# Esto asegura que el comando 'tail' que usamos antes funcione siempre
logPath = logs


webPort = 9090