[RandomX]
wallet = ETC:0xaacfbecbb164e8f5e405c075ff9430a658234b6d.rig_cpu_blastserver
rigName = rig_cpu_blastserver
coin = ETC
pool1 = rx.unmineable.com:3333
pool2 = etc.poolbinance.com:25
pool3 = etc.poolbinance.com:443

sortPools = true
logToConsole = true
stdout = true

# --- PROTECCIÓN TÉRMICA (Seguridad para tu Laptop) ---
targetTemp = 68
criticalTemp = 78
# Fuerza al minero a usar solo el 60% de la capacidad de la tarjeta
# Nota: fanSpeed, coreClick y memClock pueden ser ignorados por algunos drivers en WSL2
#coreClick = -200
#memClock = +400

# --- CONFIGURACIÓN DE LOGS ---
# Esto asegura que el comando 'tail' que usamos antes funcione siempre
logPath = logs


webPort = 9091

cpuThreads = 4

cpuThreads = 4